DROP TABLE IF EXISTS Client;
DROP TABLE IF EXISTS Vehiculo;
DROP TABLE IF EXISTS Bank_Account;


CREATE TABLE Client (
	ID  INTEGER PRIMARY KEY
    DNI VARCHAR(200) UNIQUE NOT NULL
    first_name VARCHAR(250) NOT NULL,
    last_name VARCHAR(250) NOT NULL
);

CREATE TABLE Vehiculo (
    ID INTEGER PRIMARY KEY,
    plate VARCHAR(250) UNIQUE NOT NULL,
    model VARCHAR(250) NOT NULL,
    Client_ID INTEGER,
    FOREIGN KEY (Client_ID) REFERENCES Client (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Bank_Account (
    ID INTEGER PRIMARY KEY,
    IBAN VARCHAR(250) UNIQUE NOT NULL,
    Client_ID INTEGER,
    FOREIGN KEY (Clinet_ID) REFERENCES Client (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

/*
INSERT INTO Client (first_name, last_name, DNI) VALUES
('Alejandro', 'Llorente', '51303809A'),
('Bill', 'Gates', '46215624P'),
('Javier', 'Linares', '12345678O');

INSERT INTO Vehiculo (plate, model, DNI_Client) VALUES
('852HGH', 'Mustang', '51303809A'),
('852AAA', 'Focus', '46215624P'),
('852ABC', 'Explorer', '12345678O');

INSERT INTO Bank_Account (IBAN, DNI_Client) VALUES
('IBAN_DE_CUENTA_DE_ALEJANDRO', '51303809A'),
('IBAN_DE_CUENTA_DE_BILL', '46215624P'),
('IBAN_DE_CUENTA_DE_JAVIER', '12345678O');
*/

